services:
  api:
    build: .
    ports:
      - "5003:5002"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/express-csv
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_DATABASE: express-csv
      DB_DBPORT: 5432


  db:
    image: postgres:latest
    restart: always
    container_name: "${COMPOSE_PROJECT_NAME}-postgres-db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: express-csv
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    volumes:
      - pg_data:/var/lib/postgresql/data



volumes:
  pg_data:
